/*----- PROTECTED REGION ID(LinacCoolingStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        LinacCoolingStateMachine.cpp
//
// description : State machine file for the LinacCooling class
//
// project :     Linac cooling
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <LinacCooling.h>

/*----- PROTECTED REGION END -----*/	//	LinacCooling::LinacCoolingStateMachine.cpp

//================================================================
//  States   |  Description
//================================================================
//  ON       |  *
//  OFF      |  *
//  FAULT    |  *
//  UNKNOWN  |  


namespace LinacCooling_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : LinacCooling::is_WaterTemp_allowed()
 *	Description : Execution allowed for WaterTemp attribute
 */
//--------------------------------------------------------
bool LinacCooling::is_WaterTemp_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for WaterTemp attribute in read access.
	/*----- PROTECTED REGION ID(LinacCooling::WaterTempStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LinacCooling::WaterTempStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LinacCooling::is_PBuncherTemp_allowed()
 *	Description : Execution allowed for PBuncherTemp attribute
 */
//--------------------------------------------------------
bool LinacCooling::is_PBuncherTemp_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for PBuncherTemp attribute in read access.
	/*----- PROTECTED REGION ID(LinacCooling::PBuncherTempStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LinacCooling::PBuncherTempStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LinacCooling::is_BuncherTemp_allowed()
 *	Description : Execution allowed for BuncherTemp attribute
 */
//--------------------------------------------------------
bool LinacCooling::is_BuncherTemp_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for BuncherTemp attribute in read access.
	/*----- PROTECTED REGION ID(LinacCooling::BuncherTempStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LinacCooling::BuncherTempStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LinacCooling::is_SectionTemp_allowed()
 *	Description : Execution allowed for SectionTemp attribute
 */
//--------------------------------------------------------
bool LinacCooling::is_SectionTemp_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for SectionTemp attribute in read access.
	/*----- PROTECTED REGION ID(LinacCooling::SectionTempStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LinacCooling::SectionTempStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : LinacCooling::is_Reset_allowed()
 *	Description : Execution allowed for Reset attribute
 */
//--------------------------------------------------------
bool LinacCooling::is_Reset_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Reset command.
	/*----- PROTECTED REGION ID(LinacCooling::ResetStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LinacCooling::ResetStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(LinacCooling::LinacCoolingStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	LinacCooling::LinacCoolingStateAllowed.AdditionalMethods

}	//	End of namespace
