/*----- PROTECTED REGION ID(SimurelayStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        SimurelayStateMachine.cpp
//
// description : State machine file for the Simurelay class
//
// project :     simulation relay server
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <Simurelay.h>

/*----- PROTECTED REGION END -----*/	//	Simurelay::SimurelayStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  OPEN    |  
//  CLOSE   |  
//  FAULT   |  


namespace Simurelay_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Simurelay::is_Open_allowed()
 *	Description : Execution allowed for Open attribute
 */
//--------------------------------------------------------
bool Simurelay::is_Open_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Open command.
	/*----- PROTECTED REGION ID(Simurelay::OpenStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Simurelay::OpenStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Simurelay::is_Close_allowed()
 *	Description : Execution allowed for Close attribute
 */
//--------------------------------------------------------
bool Simurelay::is_Close_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Close command.
	/*----- PROTECTED REGION ID(Simurelay::CloseStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Simurelay::CloseStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Simurelay::is_Pulse_allowed()
 *	Description : Execution allowed for Pulse attribute
 */
//--------------------------------------------------------
bool Simurelay::is_Pulse_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Pulse command.
	/*----- PROTECTED REGION ID(Simurelay::PulseStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Simurelay::PulseStateAllowed
	return true;
}

}	//	End of namespace
