/*----- PROTECTED REGION ID(GenericMultiChannelStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id: GenericMultiChannelStateMachine.cpp,v 1.2 2013-08-08 11:58:05 tappret Exp $";
//=============================================================================
//
// file :        GenericMultiChannelStateMachine.cpp
//
// description : State machine file for the GenericMultiChannel class
//
// project :     TangoMultiChannel
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author: tappret $
//
// $Revision: 1.2 $
// $Date: 2013-08-08 11:58:05 $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <GenericMultiChannel.h>

/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::GenericMultiChannelStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  Data collection is ok.
//  ALARM   |  Data collection encountered a problem.


namespace GenericMultiChannel_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannel::is_Sum_allowed()
 *	Description : Execution allowed for Sum attribute
 */
//--------------------------------------------------------
bool GenericMultiChannel::is_Sum_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Sum attribute in read access.
	/*----- PROTECTED REGION ID(GenericMultiChannel::SumStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::SumStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannel::is_Mean_allowed()
 *	Description : Execution allowed for Mean attribute
 */
//--------------------------------------------------------
bool GenericMultiChannel::is_Mean_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Mean attribute in read access.
	/*----- PROTECTED REGION ID(GenericMultiChannel::MeanStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::MeanStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannel::is_RMS_allowed()
 *	Description : Execution allowed for RMS attribute
 */
//--------------------------------------------------------
bool GenericMultiChannel::is_RMS_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for RMS attribute in read access.
	/*----- PROTECTED REGION ID(GenericMultiChannel::RMSStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::RMSStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannel::is_StandardDeviation_allowed()
 *	Description : Execution allowed for StandardDeviation attribute
 */
//--------------------------------------------------------
bool GenericMultiChannel::is_StandardDeviation_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for StandardDeviation attribute in read access.
	/*----- PROTECTED REGION ID(GenericMultiChannel::StandardDeviationStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::StandardDeviationStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannel::is_DataAcquisitionDuration_allowed()
 *	Description : Execution allowed for DataAcquisitionDuration attribute
 */
//--------------------------------------------------------
bool GenericMultiChannel::is_DataAcquisitionDuration_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for DataAcquisitionDuration attribute in read access.
	/*----- PROTECTED REGION ID(GenericMultiChannel::DataAcquisitionDurationStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::DataAcquisitionDurationStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannel::is_SubDevicesNames_allowed()
 *	Description : Execution allowed for SubDevicesNames attribute
 */
//--------------------------------------------------------
bool GenericMultiChannel::is_SubDevicesNames_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for SubDevicesNames attribute in read access.
	/*----- PROTECTED REGION ID(GenericMultiChannel::SubDevicesNamesStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::SubDevicesNamesStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannel::is_SubDevicesStates_allowed()
 *	Description : Execution allowed for SubDevicesStates attribute
 */
//--------------------------------------------------------
bool GenericMultiChannel::is_SubDevicesStates_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for SubDevicesStates attribute in read access.
	/*----- PROTECTED REGION ID(GenericMultiChannel::SubDevicesStatesStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::SubDevicesStatesStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannel::is_AttributesNames_allowed()
 *	Description : Execution allowed for AttributesNames attribute
 */
//--------------------------------------------------------
bool GenericMultiChannel::is_AttributesNames_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for AttributesNames attribute in read access.
	/*----- PROTECTED REGION ID(GenericMultiChannel::AttributesNamesStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::AttributesNamesStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannel::is_StoredSpectrum_allowed()
 *	Description : Execution allowed for StoredSpectrum attribute
 */
//--------------------------------------------------------
bool GenericMultiChannel::is_StoredSpectrum_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for StoredSpectrum attribute in Write access.
	/*----- PROTECTED REGION ID(GenericMultiChannel::StoredSpectrumStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::StoredSpectrumStateAllowed_WRITE

	//	Not any excluded states for StoredSpectrum attribute in read access.
	/*----- PROTECTED REGION ID(GenericMultiChannel::StoredSpectrumStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::StoredSpectrumStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannel::is_DoubleSpectrum_allowed()
 *	Description : Execution allowed for DoubleSpectrum attribute
 */
//--------------------------------------------------------
bool GenericMultiChannel::is_DoubleSpectrum_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for DoubleSpectrum attribute in read access.
	/*----- PROTECTED REGION ID(GenericMultiChannel::DoubleSpectrumStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::DoubleSpectrumStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannel::is_GetChannelsList_allowed()
 *	Description : Execution allowed for GetChannelsList attribute
 */
//--------------------------------------------------------
bool GenericMultiChannel::is_GetChannelsList_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for GetChannelsList command.
	/*----- PROTECTED REGION ID(GenericMultiChannel::GetChannelsListStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::GetChannelsListStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannel::is_On_allowed()
 *	Description : Execution allowed for On attribute
 */
//--------------------------------------------------------
bool GenericMultiChannel::is_On_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for On command.
	/*----- PROTECTED REGION ID(GenericMultiChannel::OnStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::OnStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannel::is_Off_allowed()
 *	Description : Execution allowed for Off attribute
 */
//--------------------------------------------------------
bool GenericMultiChannel::is_Off_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Off command.
	/*----- PROTECTED REGION ID(GenericMultiChannel::OffStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::OffStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannel::is_Reset_allowed()
 *	Description : Execution allowed for Reset attribute
 */
//--------------------------------------------------------
bool GenericMultiChannel::is_Reset_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Reset command.
	/*----- PROTECTED REGION ID(GenericMultiChannel::ResetStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::ResetStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannel::is_SetCurrent_allowed()
 *	Description : Execution allowed for SetCurrent attribute
 */
//--------------------------------------------------------
bool GenericMultiChannel::is_SetCurrent_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for SetCurrent command.
	/*----- PROTECTED REGION ID(GenericMultiChannel::SetCurrentStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::SetCurrentStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannel::is_ZeroCurrent_allowed()
 *	Description : Execution allowed for ZeroCurrent attribute
 */
//--------------------------------------------------------
bool GenericMultiChannel::is_ZeroCurrent_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ZeroCurrent command.
	/*----- PROTECTED REGION ID(GenericMultiChannel::ZeroCurrentStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::ZeroCurrentStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannel::is_GetExportedAttribute_allowed()
 *	Description : Execution allowed for GetExportedAttribute attribute
 */
//--------------------------------------------------------
bool GenericMultiChannel::is_GetExportedAttribute_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for GetExportedAttribute command.
	/*----- PROTECTED REGION ID(GenericMultiChannel::GetExportedAttributeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::GetExportedAttributeStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(GenericMultiChannel::GenericMultiChannelStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	GenericMultiChannel::GenericMultiChannelStateAllowed.AdditionalMethods

}	//	End of namespace
