/*----- PROTECTED REGION ID(GenericMultiChannelClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id: GenericMultiChannelClass.cpp,v 1.2 2013-08-08 11:58:05 tappret Exp $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source: /segfs/tango/cvsroot/cppserver/machine/GenericMultiChannel/GenericMultiChannelClass.cpp,v $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        GenericMultiChannelClass.cpp
//
// description : C++ source for the GenericMultiChannelClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the GenericMultiChannel once per process.
//
// project :     TangoMultiChannel
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author: tappret $
//
// $Revision: 1.2 $
// $Date: 2013-08-08 11:58:05 $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <GenericMultiChannelClass.h>

/*----- PROTECTED REGION END -----*/	//	GenericMultiChannelClass.cpp

//-------------------------------------------------------------------
/**
 *	Create GenericMultiChannelClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_GenericMultiChannel_class(const char *name) {
		return GenericMultiChannel_ns::GenericMultiChannelClass::init(name);
	}
}

namespace GenericMultiChannel_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
GenericMultiChannelClass *GenericMultiChannelClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		GenericMultiChannelClass::GenericMultiChannelClass(string &s)
 * description : 	constructor for the GenericMultiChannelClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
GenericMultiChannelClass::GenericMultiChannelClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering GenericMultiChannelClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(GenericMultiChannelClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannelClass::constructor

	cout2 << "Leaving GenericMultiChannelClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		GenericMultiChannelClass::~GenericMultiChannelClass()
 * description : 	destructor for the GenericMultiChannelClass
 */
//--------------------------------------------------------
GenericMultiChannelClass::~GenericMultiChannelClass()
{
	/*----- PROTECTED REGION ID(GenericMultiChannelClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannelClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		GenericMultiChannelClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
GenericMultiChannelClass *GenericMultiChannelClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new GenericMultiChannelClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		GenericMultiChannelClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
GenericMultiChannelClass *GenericMultiChannelClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		GetChannelsListClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *GetChannelsListClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "GetChannelsListClass::execute(): arrived" << endl;
	return insert((static_cast<GenericMultiChannel *>(device))->get_channels_list());
}

//--------------------------------------------------------
/**
 * method : 		OnClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *OnClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "OnClass::execute(): arrived" << endl;
	((static_cast<GenericMultiChannel *>(device))->on());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		OffClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *OffClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "OffClass::execute(): arrived" << endl;
	((static_cast<GenericMultiChannel *>(device))->off());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		ResetClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ResetClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ResetClass::execute(): arrived" << endl;
	((static_cast<GenericMultiChannel *>(device))->reset());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetCurrentClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetCurrentClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "SetCurrentClass::execute(): arrived" << endl;
	((static_cast<GenericMultiChannel *>(device))->set_current());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		ZeroCurrentClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ZeroCurrentClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ZeroCurrentClass::execute(): arrived" << endl;
	((static_cast<GenericMultiChannel *>(device))->zero_current());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		GetExportedAttributeClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *GetExportedAttributeClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "GetExportedAttributeClass::execute(): arrived" << endl;
	return insert((static_cast<GenericMultiChannel *>(device))->get_exported_attribute());
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannelClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum GenericMultiChannelClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannelClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum GenericMultiChannelClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannelClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum GenericMultiChannelClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannelClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void GenericMultiChannelClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "DataAcquisitionPeriod";
	prop_desc = "This is the period on which the AcquisitionThread tries to synchronize \naquire data. Unit is millisecond.";
	prop_def  = "1000";
	vect_data.clear();
	vect_data.push_back("1000");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "AttributesList";
	prop_desc = "This is the list of DevDouble attributes that will be collected by the\nacquisition thread.";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "AttributesSpectrumName";
	prop_desc = "This is the name of the spectrum attribute that will show collected \nattributes.";
	prop_def  = "AttributesRead";
	vect_data.clear();
	vect_data.push_back("AttributesRead");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "DeviceTimeOut";
	prop_desc = "This is the maximum amount of time spent to wait for device answer.\nThis property should be coherent (lesser) with the device property\nDataAcquisitionPeriod. Unit is millisecond.";
	prop_def  = "250";
	vect_data.clear();
	vect_data.push_back("250");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannelClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void GenericMultiChannelClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("TangoMultiChannel");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("This class tries to be a generic Tango multichannel device server.");
	str_desc.push_back("It collects DevDouble data from different devices and compute some common");
	str_desc.push_back("operation on it : sum, mean, RMS and standard deviation.");
	str_desc.push_back("The collected data are also provided into a spectrum attribute.");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("GenericMultiChannel");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannelClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void GenericMultiChannelClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(GenericMultiChannelClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannelClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new GenericMultiChannel(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		GenericMultiChannel *dev = static_cast<GenericMultiChannel *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(GenericMultiChannelClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannelClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannelClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void GenericMultiChannelClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(GenericMultiChannelClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannelClass::attribute_factory_before
	//	Attribute : Sum
	SumAttrib	*sum = new SumAttrib();
	Tango::UserDefaultAttrProp	sum_prop;
	sum_prop.set_description("This is the Sum of all collected attributes.");
	sum_prop.set_label("Sum");
	//	unit	not set for Sum
	//	standard_unit	not set for Sum
	//	display_unit	not set for Sum
	//	format	not set for Sum
	//	max_value	not set for Sum
	//	min_value	not set for Sum
	//	max_alarm	not set for Sum
	//	min_alarm	not set for Sum
	//	max_warning	not set for Sum
	//	min_warning	not set for Sum
	//	delta_t	not set for Sum
	//	delta_val	not set for Sum
	
	sum->set_default_properties(sum_prop);
	//	Not Polled
	sum->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(sum);

	//	Attribute : Mean
	MeanAttrib	*mean = new MeanAttrib();
	Tango::UserDefaultAttrProp	mean_prop;
	mean_prop.set_description("This is the Mean of all collected attributes.");
	mean_prop.set_label("Mean");
	//	unit	not set for Mean
	//	standard_unit	not set for Mean
	//	display_unit	not set for Mean
	//	format	not set for Mean
	//	max_value	not set for Mean
	//	min_value	not set for Mean
	//	max_alarm	not set for Mean
	//	min_alarm	not set for Mean
	//	max_warning	not set for Mean
	//	min_warning	not set for Mean
	//	delta_t	not set for Mean
	//	delta_val	not set for Mean
	
	mean->set_default_properties(mean_prop);
	//	Not Polled
	mean->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(mean);

	//	Attribute : RMS
	RMSAttrib	*rms = new RMSAttrib();
	Tango::UserDefaultAttrProp	rms_prop;
	rms_prop.set_description("This is the RMS of all collected attributes.");
	rms_prop.set_label("RMS");
	//	unit	not set for RMS
	//	standard_unit	not set for RMS
	//	display_unit	not set for RMS
	//	format	not set for RMS
	//	max_value	not set for RMS
	//	min_value	not set for RMS
	//	max_alarm	not set for RMS
	//	min_alarm	not set for RMS
	//	max_warning	not set for RMS
	//	min_warning	not set for RMS
	//	delta_t	not set for RMS
	//	delta_val	not set for RMS
	
	rms->set_default_properties(rms_prop);
	//	Not Polled
	rms->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(rms);

	//	Attribute : StandardDeviation
	StandardDeviationAttrib	*standarddeviation = new StandardDeviationAttrib();
	Tango::UserDefaultAttrProp	standarddeviation_prop;
	standarddeviation_prop.set_description("This is the Standard Deviation of the collected attributes.");
	standarddeviation_prop.set_label("Standard Deviation");
	//	unit	not set for StandardDeviation
	//	standard_unit	not set for StandardDeviation
	//	display_unit	not set for StandardDeviation
	//	format	not set for StandardDeviation
	//	max_value	not set for StandardDeviation
	//	min_value	not set for StandardDeviation
	//	max_alarm	not set for StandardDeviation
	//	min_alarm	not set for StandardDeviation
	//	max_warning	not set for StandardDeviation
	//	min_warning	not set for StandardDeviation
	//	delta_t	not set for StandardDeviation
	//	delta_val	not set for StandardDeviation
	
	standarddeviation->set_default_properties(standarddeviation_prop);
	//	Not Polled
	standarddeviation->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(standarddeviation);

	//	Attribute : DataAcquisitionDuration
	DataAcquisitionDurationAttrib	*dataacquisitionduration = new DataAcquisitionDurationAttrib();
	Tango::UserDefaultAttrProp	dataacquisitionduration_prop;
	dataacquisitionduration_prop.set_description("Time used by the acquisition thread to acquire datas.");
	dataacquisitionduration_prop.set_label("Data acq. duration");
	//	unit	not set for DataAcquisitionDuration
	//	standard_unit	not set for DataAcquisitionDuration
	dataacquisitionduration_prop.set_display_unit("ms");
	//	format	not set for DataAcquisitionDuration
	//	max_value	not set for DataAcquisitionDuration
	//	min_value	not set for DataAcquisitionDuration
	//	max_alarm	not set for DataAcquisitionDuration
	//	min_alarm	not set for DataAcquisitionDuration
	//	max_warning	not set for DataAcquisitionDuration
	//	min_warning	not set for DataAcquisitionDuration
	//	delta_t	not set for DataAcquisitionDuration
	//	delta_val	not set for DataAcquisitionDuration
	
	dataacquisitionduration->set_default_properties(dataacquisitionduration_prop);
	//	Not Polled
	dataacquisitionduration->set_disp_level(Tango::EXPERT);
	//	Not Memorized
	att_list.push_back(dataacquisitionduration);

	//	Attribute : SubDevicesNames
	SubDevicesNamesAttrib	*subdevicesnames = new SubDevicesNamesAttrib();
	Tango::UserDefaultAttrProp	subdevicesnames_prop;
	subdevicesnames_prop.set_description("Name of the sub devices actually read by acquisition thread.");
	subdevicesnames_prop.set_label("Sub devices names");
	//	unit	not set for SubDevicesNames
	//	standard_unit	not set for SubDevicesNames
	//	display_unit	not set for SubDevicesNames
	//	format	not set for SubDevicesNames
	//	max_value	not set for SubDevicesNames
	//	min_value	not set for SubDevicesNames
	//	max_alarm	not set for SubDevicesNames
	//	min_alarm	not set for SubDevicesNames
	//	max_warning	not set for SubDevicesNames
	//	min_warning	not set for SubDevicesNames
	//	delta_t	not set for SubDevicesNames
	//	delta_val	not set for SubDevicesNames
	
	subdevicesnames->set_default_properties(subdevicesnames_prop);
	//	Not Polled
	subdevicesnames->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(subdevicesnames);

	//	Attribute : SubDevicesStates
	SubDevicesStatesAttrib	*subdevicesstates = new SubDevicesStatesAttrib();
	Tango::UserDefaultAttrProp	subdevicesstates_prop;
	subdevicesstates_prop.set_description("State of the attributes actually read by acquisition thread.");
	subdevicesstates_prop.set_label("Sub devices states");
	//	unit	not set for SubDevicesStates
	//	standard_unit	not set for SubDevicesStates
	//	display_unit	not set for SubDevicesStates
	//	format	not set for SubDevicesStates
	//	max_value	not set for SubDevicesStates
	//	min_value	not set for SubDevicesStates
	//	max_alarm	not set for SubDevicesStates
	//	min_alarm	not set for SubDevicesStates
	//	max_warning	not set for SubDevicesStates
	//	min_warning	not set for SubDevicesStates
	//	delta_t	not set for SubDevicesStates
	//	delta_val	not set for SubDevicesStates
	
	subdevicesstates->set_default_properties(subdevicesstates_prop);
	//	Not Polled
	subdevicesstates->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(subdevicesstates);

	//	Attribute : AttributesNames
	AttributesNamesAttrib	*attributesnames = new AttributesNamesAttrib();
	Tango::UserDefaultAttrProp	attributesnames_prop;
	attributesnames_prop.set_description("Name of the attributes actually read by acquisition thread.");
	attributesnames_prop.set_label("Attributes name");
	//	unit	not set for AttributesNames
	//	standard_unit	not set for AttributesNames
	//	display_unit	not set for AttributesNames
	//	format	not set for AttributesNames
	//	max_value	not set for AttributesNames
	//	min_value	not set for AttributesNames
	//	max_alarm	not set for AttributesNames
	//	min_alarm	not set for AttributesNames
	//	max_warning	not set for AttributesNames
	//	min_warning	not set for AttributesNames
	//	delta_t	not set for AttributesNames
	//	delta_val	not set for AttributesNames
	
	attributesnames->set_default_properties(attributesnames_prop);
	//	Not Polled
	attributesnames->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(attributesnames);

	//	Attribute : StoredSpectrum
	StoredSpectrumAttrib	*storedspectrum = new StoredSpectrumAttrib();
	Tango::UserDefaultAttrProp	storedspectrum_prop;
	//	description	not set for StoredSpectrum
	storedspectrum_prop.set_label("Stored spectrum");
	//	unit	not set for StoredSpectrum
	//	standard_unit	not set for StoredSpectrum
	//	display_unit	not set for StoredSpectrum
	//	format	not set for StoredSpectrum
	//	max_value	not set for StoredSpectrum
	//	min_value	not set for StoredSpectrum
	//	max_alarm	not set for StoredSpectrum
	//	min_alarm	not set for StoredSpectrum
	//	max_warning	not set for StoredSpectrum
	//	min_warning	not set for StoredSpectrum
	//	delta_t	not set for StoredSpectrum
	//	delta_val	not set for StoredSpectrum
	
	storedspectrum->set_default_properties(storedspectrum_prop);
	//	Not Polled
	storedspectrum->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(storedspectrum);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(GenericMultiChannelClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannelClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannelClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void GenericMultiChannelClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(GenericMultiChannelClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannelClass::pipe_factory_before
	/*----- PROTECTED REGION ID(GenericMultiChannelClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannelClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannelClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void GenericMultiChannelClass::command_factory()
{
	/*----- PROTECTED REGION ID(GenericMultiChannelClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannelClass::command_factory_before


	//	Command GetChannelsList
	GetChannelsListClass	*pGetChannelsListCmd =
		new GetChannelsListClass("GetChannelsList",
			Tango::DEV_VOID, Tango::DEVVAR_STRINGARRAY,
			"",
			"list of channels controlled by this device",
			Tango::EXPERT);
	command_list.push_back(pGetChannelsListCmd);

	//	Command On
	OnClass	*pOnCmd =
		new OnClass("On",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pOnCmd);

	//	Command Off
	OffClass	*pOffCmd =
		new OffClass("Off",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pOffCmd);

	//	Command Reset
	ResetClass	*pResetCmd =
		new ResetClass("Reset",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pResetCmd);

	//	Command SetCurrent
	SetCurrentClass	*pSetCurrentCmd =
		new SetCurrentClass("SetCurrent",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::EXPERT);
	command_list.push_back(pSetCurrentCmd);

	//	Command ZeroCurrent
	ZeroCurrentClass	*pZeroCurrentCmd =
		new ZeroCurrentClass("ZeroCurrent",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::EXPERT);
	command_list.push_back(pZeroCurrentCmd);

	//	Command GetExportedAttribute
	GetExportedAttributeClass	*pGetExportedAttributeCmd =
		new GetExportedAttributeClass("GetExportedAttribute",
			Tango::DEV_VOID, Tango::DEV_STRING,
			"",
			"Current or Voltage depending device property",
			Tango::EXPERT);
	command_list.push_back(pGetExportedAttributeCmd);

	/*----- PROTECTED REGION ID(GenericMultiChannelClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannelClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		GenericMultiChannelClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void GenericMultiChannelClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(GenericMultiChannelClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannelClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		GenericMultiChannelClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void GenericMultiChannelClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		GenericMultiChannel *dev = static_cast<GenericMultiChannel *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(GenericMultiChannelClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	GenericMultiChannelClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : GenericMultiChannelClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *GenericMultiChannelClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(GenericMultiChannelClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	GenericMultiChannelClass::Additional Methods
} //	namespace
