/*----- PROTECTED REGION ID(LinacRF::ClassFactory.cpp) ENABLED START -----*/
static const char *RcsId = "$Header: /segfs/tango/cvsroot/cppserver/machine/linac/LinacRF/ClassFactory.cpp,v 1.4 2006/06/22 12:57:23 bourtemb Exp $";
//+=============================================================================
//
// file :        ClassFactory.cpp
//
// description : C++ source for the class_factory method of the DServer
//               device class. This method is responsible to create
//               all class singletin for a device server. It is called
//               at device server startup
//
// project :     TANGO Device Server
//
// $Author: bourtemb $
//
// $Revision: 1.4 $
//
// $Log: ClassFactory.cpp,v $
// Revision 1.4  2006/06/22 12:57:23  bourtemb
// #undef WRITE before some tango includes to avoid conflicts with taco and remove add_class(WagoRelay)
//
// Revision 1.3  2005/09/20 13:58:35  bourtemb
// first WIN32 SIMU Version
//
// Revision 1.2  2005/06/02 13:01:41  bourtemb
// add the possibility to handle SAdc150, SDac712, AdcDac and WagoRelay devices internally
//
// Revision 1.1.1.1  2005/05/18 11:35:01  bourtemb
// Imported using TkCVS
//
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESLinacRF
//=============================================================================


#include <tango.h>
#include <LinacRFClass.h>
#ifndef SIMU
#undef WRITE
#include <SAdc150Class.h>
#include <SDac712Class.h>
#include <AdcDacClass.h>
#endif

/**
 *	Create LinacRFClass singleton and store it in DServer object.
 */

void Tango::DServer::class_factory()
{
#ifndef SIMU
	add_class(SAdc150_ns::SAdc150Class::init("SAdc150"));
	add_class(SDac712_ns::SDac712Class::init("SDac712"));
	add_class(AdcDac_ns::AdcDacClass::init("AdcDac"));
#endif
	add_class(LinacRF_ns::LinacRFClass::init("LinacRF"));

}
/*----- PROTECTED REGION END -----*/	//	LinacRF::ClassFactory.cpp
