version: '1'
services:

  archiving:
    image: archiving:latest
    hostname: tangobox-archiving
    command: supervisord -c /etc/supervisord.archiving.conf
#    environment:
    volumes:
      - /usr/tango-cs/Dockerfiles/composer/config/supervisord/supervisord.archiving.conf:/etc:ro
    extra_hosts:
      - "TangoBox-VM:172.18.0.1"
    links:
      - sardana:tangobox-sardana
      - sim:tangobox-sim
      - com:tangobox-com
      - web:tangobox-web
    networks:
      vpcbr:
        ipv4_address: 172.18.0.2

  sim:
    image: sim:latest
    hostname: tangobox-sim
    command: supervisord -c /etc/supervisord.sim.conf
#    environment: 
    volumes:
      - /usr/tango-cs/Dockerfiles/composer/config/supervisord/supervisord.sim.conf:/etc:ro
    extra_hosts:
      - "TangoBox-VM:172.18.0.1"
    links:
      - com:tangobox-com
      - archiving:tangobox-archiving
      - web:tangobox-web
      - sardana:tangobox-sardana
    networks:
      vpcbr:
        ipv4_address: 172.18.0.3
      
  com:
    image: com:latest
    hostname: tangobox-com
    command: supervisord -c /etc/supervisord.com.conf
#    environment: 
    volumes:
      - /usr/tango-cs/Dockerfiles/composer/config/supervisord/supervisord.com.conf:/etc:ro
    extra_hosts:
      - "TangoBox-VM:172.18.0.1"
    links:
      - sim:tangobox-sim
      - archiving:tangobox-archiving
      - web:tangobox-web
      - sardana:tangobox-sardana
    networks:
      vpcbr:
        ipv4_address: 172.18.0.4

  web:
    image: web:latest
    hostname: tangobox-web
    command: supervisord -c /etc/supervisord.web.conf
#    environment: 
    volumes:
      - /usr/tango-cs/Dockerfiles/composer/config/supervisord/supervisord.web.conf:/etc:ro
    extra_hosts:
      - "TangoBox-VM:172.18.0.1"
    links:
      - sim:tangobox-sim
      - com:tangobox-com
      - archiving:tangobox-archiving
      - sardana:tangobox-sardana
    networks:
      vpcbr:
        ipv4_address: 172.18.0.5

  sardana:
    image: sardana:latest
    hostname: tangobox-sardana
    command: supervisord -c /etc/supervisord.sardana.conf
#    environment: 
    volumes:
      - /usr/tango-cs/Dockerfiles/composer/config/supervisord/supervisord.sardana.conf:/etc:ro
    extra_hosts:
      - "TangoBox-VM:172.18.0.1"
    links: 
      - com:tangobox-com
      - archiving:tangobox-archiving
      - sim:tangobox-sim
      - web:tangobox-web
    networks:
      vpcbr:
        ipv4_address: 172.18.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
        - gateway: 172.18.0.1
