version: '1'
services:

  archiving:
    image: archiving:latest
    hostname: tangobox-archiving
    command: supervisord -c /etc/supervisord.archiving.conf
#    environment:
    volumes:
      - /usr/tango-cs/Dockerfiles/composer/config/supervisord/supervisor.archiving.conf:/etc:ro
    extra_hosts:
      - "TangoBox-VM:10.0.2.15"
    links:
      - base:tangobox-base  
      - sardana:tangobox-sardana
      - sim:tangobox-sim
      - com:tangobox-com
      - web:tangobox-web
      
  base :
    image: base:latest
    hostname: tangobox-base
    command: supervisord -c /etc/supervisord.base.conf
#    environment: 
    volumes:
      - /usr/tango-cs/Dockerfiles/composer/config/supervisord/supervisor.base.conf:/etc:ro
    extra_hosts:
      - "TangoBox-VM:10.0.2.15"
    links:
      - sardana:tangobox-sardana
      - sim:tangobox-sim  
      - com:tangobox-com
      - archiving:tangobox-archiving
      - web:tangobox-web

  com:
    image: com:latest
    hostname: tangobox-com
    command: supervisord -c /etc/supervisord.com.conf
#    environment: 
    volumes:
      - /usr/tango-cs/Dockerfiles/composer/config/supervisord/supervisor.com.conf:/etc:ro
    extra_hosts:
      - "TangoBox-VM:10.0.2.15"
    links:
      - base:tangobox-base  
      - sim:tangobox-sim
      - archiving:tangobox-archiving
      - web:tangobox-web
      - sardana:tangobox-sardana

  sardana:
    image: sardana:latest
    hostname: tangobox-sardana
    command: supervisord -c /etc/supervisord.sardana.conf
#    environment: 
    volumes:
      - /usr/tango-cs/Dockerfiles/composer/config/supervisord/supervisor.sardana.conf:/etc:ro
    extra_hosts:
      - "TangoBox-VM:10.0.2.15"
    links:
      - base:tangobox-base  
      - com:tangobox-com
      - archiving:tangobox-archiving
      - web:tangobox-web


  sim:
    image: sim:latest
    hostname: tangobox-sim
    command: supervisord -c /etc/supervisord.sim.conf
#    environment: 
    volumes:
      - /usr/tango-cs/Dockerfiles/composer/config/supervisord/supervisor.sim.conf:/etc:ro
    extra_hosts:
      - "TangoBox-VM:10.0.2.15"
    links:
      - base:tangobox-base  
      - com:tangobox-com
      - archiving:tangobox-archiving
      - web:tangobox-web
      - sardana:tangobox-sardana

  web:
    image: web:latest
    hostname: tangobox-web
    command: supervisord -c /etc/supervisord.web.conf
#    environment: 
    volumes:
      - /usr/tango-cs/Dockerfiles/composer/config/supervisord/supervisor.web.conf:/etc:ro
    extra_hosts:
      - "TangoBox-VM:10.0.2.15"
    links:
      - base:tangobox-base  
      - sim:tangobox-sim
      - com:tangobox-com
      - archiving:tangobox-archiving
      - sardana:tangobox-sardana